export interface UserProxy {
    IdUsuario: string,
    Usuario: string,
    Telefone: string,
    pontuacao: string,
    Nome: string,
    Longitude: number,
    Latitude: number,
    FotoPerfil: string,
    Email: string,
    DataNascimento: Date,
    dadosConquista: { Nome: string, Descricao: string}[],
    CPF: string,
    Rua: string,
    Cidade: string,
    Estado: string,
    Bairro: string,
    Numero: string,
}
